---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Install required packages
  yum:
    name:
      - jq
      - vim
      - bc 
      - wget
    state: latest
- name: Install required packages via pip
  pip:
    name:
      - jmespath
    state: latest
    executable: "{{ ansible_pip_executable }}"
