---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Install required packages
  yum:
    name:
      - jq
      - vim
      - bc 
      - wget
    state: latest
- name: Install required packages via pip
  shell: /usr/bin/python3 -m pip install jmespath