---
- name: "PREP | Upgrade all packages"
  apt:
    name: '*'
    state: latest

- name: "PREP | Install required packages"
  apt:
    name:
      - jq
      - vim
      - bc 
      - wget
    state: latest

- name: "PREP | Install required packages via pip"
  pip:
    name:
      - jmespath
      - pymongo
    state: latest
    executable: "{{ ansible_pip_executable }}"
