---
prep_conf: true
mongostig_cat1: true
mongostig_cat2: true
mongostig_cat3: true 

mongo_owner: root
mongo_group: root
mongo_dba: admin
mongo_dba_password: admin
mongo_host: localhost
mongo_port: 27017
mongo_permissions: 0600
authentication_mechanism: 
  - SCRAM-SHA-256

mongod_config_path: /etc/mongod.conf

#audit_log_destination choose "file" or "syslog"
audit_log_destination: file
mongo_audit_directory_path: /var/log/mongodb/audit/
mongo_audit_file_path: /var/log/mongodb/audit/auditLog.bson

certificate_key_file_dest: /etc/ssl/mongodb.pem
certificate_key_file_src: ../../../../certificates/mongodb.pem
ca_file_dest: /etc/ssl/caToValidateClientCertificates.pem
ca_file_src: ../../../../certificates/dod_CAs.pem

data_file_directory_path: /data/db/

max_incoming_connections: 800000

KMIP_server_host_name: 
KMIP_server_port: 
KMIP_server_ca_file: 
KMIP_client_certificate_file: 