---
# defaults file for mongo-stig
prep_conf: true
mongostig_cat1: true
mongostig_cat2: true
mongostig_cat3: true 
mongo_user: root
mongo_group: root
#audit_log_destination | "file" or "syslog"
audit_log_destination: "file"
mongod_config_path: "/etc/mongod.conf"
mongo_audit_directory_path: "/var/log/mongodb/audit"
mongo_audit_file_path: "/var/log/mongodb/audit/auditLog.bson"
certificate_key_file_path: "/etc/ssl/mongodb.pem"
ca_file_path: "/etc/ssl/caToValidateClientCertificates.pem"
data_file_directory_path: "/var/lib/mongo"
max_incoming_connections: 800000
KMIP_server_host_name: ""
KMIP_server_port: ""
KMIP_server_ca_file: ""
KMIP_client_certificate_file: ""