---
prep_conf: true
enterprise_edition: true
fips_mode: true
mongostig_cat1: true
mongostig_cat2: true
# If any data is PII, classified or is deemed by the organization the need to be encrypted at rest.
encryption_at_rest: false
kmip_enabled: false

mongo_owner: root
mongo_group: root
mongo_dba: admin
mongo_dba_password: admin
mongo_host: localhost
mongo_port: 27017
mongo_auth_source: admin
mongo_permissions: 0600
mongo_super_users:
  - "admin.admin"
mongo_users:
  - "test.myTester"
  - "products.myRoleTestUser"
  - "loler.myTester"
  - "loler.bruhburh"
  - "imhere.bruhburh"

authentication_mechanism: 
  - SCRAM-SHA-256

mongod_config_path: /etc/mongod.conf

# Set `audit_log_destination` to either "file" or "syslog"
audit_log_destination: file
mongo_audit_directory_path: /var/log/mongodb/audit/
mongo_audit_file_path: /var/log/mongodb/audit/auditLog.bson

certificate_key_file_dest: /etc/ssl/mongodb.pem
certificate_key_file_src: ../../../../certificates/mongodb.pem
ca_file_dest: /etc/ssl/CA_bundle.pem
ca_file_src: ../../../../certificates/dod_CAs.pem

data_file_directory_path: /data/db/

max_incoming_connections: 800000

mongo_filter: "'{ atype: { $in: [ \"createCollection\", \"dropCollection\" ] } }'"

encryption_cipher_mode: AES256-GCM
KMIP_server_host_name: 
KMIP_server_port: 
KMIP_server_ca_file: 
KMIP_client_certificate_file: 

security_encryption_key_file: 