---
- hosts:
    - localhost
  roles:
    - roles/prep  # basic update and config tasks
    - rhel8STIG   # apply STIG requirement controls
  serial: 50
  user: 0
  vars:
    rhel8stig_bootloader_password_hash: 'changethispassword'
    rhel_08_040123: false
    rhel_08_040124: false
    rhel_08_040125: false