---
- name: "HIGH | SV-252139 | If passwords are used for authentication, MongoDB must transmit only encrypted representations of passwords."
  yedit:
    src: "{{ mongod_config_path }}"
    edits:
    - key: net.tls.mode
      value: requireTLS
    - key: net.tls.certificateKeyFile
      value: "{{ certificate_key_file_dest }}"
    - key: net.tls.CAFile
      value: "{{ ca_file_dest }}"
    - key: net.tls.allowInvalidCertificates
      value: false
    - key: net.tls.allowConnectionsWithoutCertificates
      value: false
  ignore_errors: true
  when: enterprise_edition
  tags:
    - cat1
    - high
    - SV-252139
    - enterprise

- name: "HIGH | SV-252146 | MongoDB must use NIST FIPS 140-2 or 140-3 validated cryptographic modules for cryptographic operations."
  yedit:
      src: "{{ mongod_config_path }}"
      key: net.tls.FIPSMode
      value: true
  ignore_errors: true
  when: enterprise_edition and fips_mode
  tags:
    - cat1
    - high
    - SV-252146
    - enterprise
    - fips

- name: "HIGH | SV-252149 | MongoDB must integrate with an organization-level authentication/access mechanism providing account management and automation for all users, groups, roles, and any other principals."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.authorization
      value: enabled
  ignore_errors: true
  when: enterprise_edition
  tags:
    - cat1
    - high
    - SV-252149
    - enterprise

- name: "HIGH | SV-252150 | MongoDB must enforce approved authorizations for logical access to information and system resources in accordance with applicable access control policies."
  debug:
    msg: "Consult the STIG documentation to manually address and verify compliance for SV-252170."
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252150
    - manual

- name: "HIGH | SV-252152 | MongoDB software installation account must be restricted to authorized users."
  debug:
    msg: "Consult the STIG documentation to manually address and verify compliance for SV-252152."
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252152
    - manual

- name: "HIGH | SV-252158 | If passwords are used for authentication, MongoDB must implement LDAP or Kerberos for authentication to enforce the DoD standards for password complexity and lifetime."
  debug:
    msg: "Consult the STIG documentation to manually address and verify compliance for SV-252158."
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252158
    - manual

- name: "HIGH | SV-252159 | If passwords are used for authentication, MongoDB must store only hashed, salted representations of passwords."
  yedit:
      src: "{{ mongod_config_path }}"
      key: setParameter.authenticationMechanisms
      value: "{{ authentication_mechanism | join(',') }}"
  ignore_errors: true
  when: enterprise_edition
  tags:
    - cat1
    - high
    - SV-252159
    - enterprise

- name: "HIGH | SV-252160 | MongoDB must enforce authorized access to all PKI private keys stored/utilized by MongoDB."
  block:
    - name: "HIGH | SV-252160 | MongoDB must enforce authorized access to all PKI private keys stored/utilized by MongoDB. | Certificate Key File"
      ansible.builtin.file: 
        path: "{{ certificate_key_file_dest }}"
        owner: "{{ mongo_owner }}"
        group: "{{ mongo_group }}"
        mode: "{{ mongo_permissions }}"
    - name: "HIGH | SV-252160 | MongoDB must enforce authorized access to all PKI private keys stored/utilized by MongoDB. | CA File"
      ansible.builtin.file: 
        path: "{{ ca_file_dest }}"
        owner: "{{ mongo_owner }}"
        group: "{{ mongo_group }}"
        mode: "{{ mongo_permissions }}"
  when: enterprise_edition
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252160
    - enterprise

- name: "HIGH | SV-252162 | MongoDB must obscure feedback of authentication information during the authentication process to protect the information from possible exploitation/use by unauthorized individuals."
  debug:
    msg: "Consult the STIG documentation to manually address and verify compliance for SV-252162."
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252162
    - manual

- name: "HIGH | SV-252165 | MongoDB must protect the confidentiality and integrity of all information at rest."
  block: 
  - name: "HIGH | SV-252165 | MongoDB must protect the confidentiality and integrity of all information at rest. | KMIP Enabled"
    yedit:
      src: "{{ mongod_config_path }}"
      edits:
      - key: net.tls.FIPSMode
        value: true
      - key: security.encryptionCipherMode
        value: "{{ encryption_cipher_mode }}"
      - key: security.enableEncryption
        value: true
      - key: kmip.serverName
        value: "{{ KMIP_server_host_name }}"
      - key: kmip.port
        value: "{{ KMIP_server_port }}"
      - key: kimp.ServerCAFile
        value: "{{ KMIP_server_ca_file }}"
      - key: kmip.clientCertificationFile
        value: "{{ KMIP_client_certificate_file }}"
      when: kmip_enabled

  - name: "HIGH | SV-252165 | MongoDB must protect the confidentiality and integrity of all information at rest. | Local Encryption Key File"    
    yedit:
      src: "{{ mongod_config_path }}"
      edits:
      - key: net.tls.FIPSMode
        value: true
      - key: security.enableEncryption
        value: true
      - key: security.encryptionCipherMode
        value: "{{ encryption_cipher_mode }}"
      - key: security.encryptionKeyFile
        value: "{{ security_encryption_key_file }}"
      when: not kmip_enabled
  ignore_errors: true
  when: enterprise_edition and encryption_at_rest
  tags:
    - cat1
    - high
    - SV-252165
    - enterprise

- name: "HIGH | SV-252184 | MongoDB products must be a version supported by the vendor."
  debug:
    msg: "Consult the STIG documentation to manually address and verify compliance for SV-252184."
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252184
    - manual
    

- name: Print the contents of mongod.conf
  command: cat "{{ mongod_config_path }}"
  register: mongod_conf_content

- name: Display contents of mongod.conf
  debug:
    msg: "{{ mongod_conf_content.stdout }}"
