---
##### DOES NOT WORK DUE TO MISSING FILE PATHS, disabled
# - name: "HIGH | SV-252139 | If passwords are used for authentication, MongoDB must transmit only encrypted representations of passwords."
#   yedit:
#     src: "{{ mongod_config_path }}"
#     edits:
#     - key: net.tls.mode
#       value: requireTLS
#     - key: net.tls.certificateKeyFile
#       value: "{{ certificate_key_file_path }}"
#     - key: net.tls.CAFile
#       value: "{{ ca_file_path }}"
#     - key: net.tls.allowInvalidCertificates
#       value: false
#     - key: net.tls.allowConnectionsWithoutCertificates
#       value: false
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252139

##### ENTERPRISE ONLY, DISABLED FOR EASIER TESTING
# - name: "HIGH | SV-252146 | MongoDB must use NIST FIPS 140-2 or 140-3 validated cryptographic modules for cryptographic operations."
#   yedit:
#       src: "{{ mongod_config_path }}"
#       key: net.tls.FIPSMode
#       value: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252146
#     - enterprise

##### DISABLED FOR EASIER TESTING
- name: "HIGH | SV-252149 | MongoDB must integrate with an organization-level authentication/access mechanism providing account management and automation for all users, groups, roles, and any other principals."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.authorization
      value: enabled
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252149

##### MANUAL
# - name: "HIGH | SV-252150 | MongoDB must enforce approved authorizations for logical access to information and system resources in accordance with applicable access control policies."
#   commant: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252150


##### MANUAL
# - name: "HIGH | SV-252152 | MongoDB software installation account must be restricted to authorized users."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252152

##### MANUAL
# - name: "HIGH | SV-252158 | If passwords are used for authentication, MongoDB must implement LDAP or Kerberos for authentication to enforce the DoD standards for password complexity and lifetime."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252158


##### PART TWO OF THIS DOESNT EXIST IN MONGO 4+
# - name: "HIGH | SV-252159 | If passwords are used for authentication, MongoDB must store only hashed, salted representations of passwords."
#   blockinfile:
#     path: "{{ mongod_config_path }}"
#     marker: "#Rule ID SV-252159"
#     prepend_newline: true
#     insertafter: "EOF"
#     block: |
#       setParameter:
#         authenticationMechanisms: SCRAM-SHA-256
#     state: present
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252159
  
##### CHANGES TO ENTERPRISE WITH GSSAPI AND PLAIN, ASKS FOR ALL OF THEM
- name: "HIGH | SV-252159 | If passwords are used for authentication, MongoDB must store only hashed, salted representations of passwords."
  yedit:
      src: "{{ mongod_config_path }}"
      key: setParameter.authenticationMechanisms
      value: "{{ authentication_mechanism | join(',') }}"
  ignore_errors: true
  tags:
    - cat1
    - high
    - SV-252159
    - enterprise

##### FILES DONT EXIST
# - name: "HIGH | SV-252160 | MongoDB must enforce authorized access to all PKI private keys stored/utilized by MongoDB."
#   ansible.builtin.shell: |
#       chown {{ mongo_owner }}:{{ mongo_owner }} {{ certificate_key_file_path }}
#       chmod {{ mongo_permissions }} {{ certificate_key_file_path }}
#       chown {{ mongo_owner }}:{{ mongo_owner }} {{ ca_file_path }}
#       chmod {{ mongo_permissions }} {{ ca_file_path }}
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252160

##### MANUAL
# - name: "HIGH | SV-252162 | MongoDB must obscure feedback of authentication information during the authentication process to protect the information from possible exploitation/use by unauthorized individuals."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252162

##### ENTERPRISE ONLY
# - name: "HIGH | SV-252165 | MongoDB must protect the confidentiality and integrity of all information at rest."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252165
#     - enterprise

##### MANUAL
# - name: "HIGH | SV-252184 | MongoDB products must be a version supported by the vendor."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat1
#     - high
#     - SV-252184

- name: Print the contents of mongod.conf
  command: cat "{{ mongod_config_path }}"
  register: mongod_conf_content

- name: Display contents of mongod.conf
  debug:
    msg: "{{ mongod_conf_content.stdout }}"
