---
- name: "MEDIUM | SV-252134 | MongoDB must provide audit record generation for DoD-defined auditable events within all DBMS/database components."
  block:
    - name: "MEDIUM | SV-252134 | MongoDB must provide audit record generation for DoD-defined auditable events within all DBMS/database components. | syslog option"
      yedit:
        src: "{{ mongod_config_path }}"
        key: auditLog.destination
        value: "{{ audit_log_destination}}"
      when: audit_log_destination == "syslog"

    - name: "MEDIUM | SV-252134 | MongoDB must provide audit record generation for DoD-defined auditable events within all DBMS/database components. | check for file directory"
      ansible.builtin.file:
        path: "{{ mongo_audit_directory_path }}"
        state: directory
        mode: "{{ mongo_permissions }}"
      when: audit_log_destination == "file"

    - name: "MEDIUM | SV-252134 | MongoDB must provide audit record generation for DoD-defined auditable events within all DBMS/database components. | check if file exists"
      ansible.builtin.file:
        path: "{{ mongo_audit_file_path }}"
        state: touch
      when: audit_log_destination == "file"

    - name: "MEDIUM | SV-252134 | MongoDB must provide audit record generation for DoD-defined auditable events within all DBMS/database components. | file option"
      yedit:
        src: "{{ mongod_config_path }}"
        edits:
        - key: auditLog.destination
          value: file
        - key: auditLog.format
          value: BSON
        - key: auditLog.path
          value: "{{ mongo_audit_file_path }}"
      when: audit_log_destination == "file"

  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252134
    - enterprise

- name: "MEDIUM | SV-252135 | The audit information produced by MongoDB must be protected from unauthorized access."
  ansible.builtin.file: 
      path: "{{ mongo_audit_directory_path }}"
      owner: "{{ mongo_owner }}"
      group: "{{ mongo_group}}"
      mode: "{{ mongo_permissions }}"
      state: directory
      recurse: yes
  when: audit_log_destination == "file"
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252135
    - enterprise

- name: "MEDIUM | SV-252136 | MongoDB must protect its audit features from unauthorized access."
  ansible.builtin.file: 
    path: "{{ mongod_config_path }}"
    owner: "{{ mongo_owner }}"
    group: "{{ mongo_group}}"
    mode: "{{ mongo_permissions }}"
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252136

- name: "MEDIUM | SV-252137 | Unused database components that are integrated in MongoDB and cannot be uninstalled must be disabled."
  yedit:
    src: "{{ mongod_config_path }}"
    key: net.http
    state: absent
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252137

- name: "MEDIUM | SV-252138 | Unused database components that are integrated in MongoDB and cannot be uninstalled must be disabled."
  yedit:
    src: "{{ mongod_config_path }}"
    key: net.http
    state: absent
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252138

##### MANUAL??? https://github.com/mitre/crunchy-data-postgresql-stig-baseline/blob/ebc58258ba175cb1d3859fd8039e05b5b3493dda/controls/V-233524.rb#L4
# - name: "MEDIUM | SV-252140 | MongoDB must uniquely identify and authenticate non-organizational users (or processes acting on behalf of non-organizational users)."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252140

#### DOES NOT EXIST IN MONGO 6+
- name: "MEDIUM | SV-252141 | MongoDB must fail to a secure state if system initialization fails, shutdown fails, or aborts fail."
  yedit:
    src: "{{ mongod_config_path }}"
    key: storage.journal.enabled
    value: true
  when: mongodb_version.stdout is version('6.1.0', '<=', 'version_type=semver')
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252141

##### DIRECTORY DOESNT EXIST
- name: "MEDIUM | SV-252142 | MongoDB must prevent unauthorized and unintended information transfer via shared system resources."
  ansible.builtin.shell: |
      chown {{ mongo_owner }}:{{ mongo_group }} {{ mongod_config_path }}
      chmod {{ mongo_permissions }} {{ mongod_config_path }}
  # chown -R mongod:mongod {{ data_file_directory_path }}
  # chmod {{ mongo_permissions }} {{ data_file_directory_path }}
  # find {{ data_file_directory_path }}/* -type f | xargs  chmod {{ mongo_permissions }}
  # find {{ data_file_directory_path }}/* -type d | xargs  chmod {{ mongo_permissions }}
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252142

- name: "MEDIUM | SV-252143 | MongoDB and associated applications must reserve the use of dynamic code execution for situations that require it."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.javascriptEnabled
      value: false
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252143

##### MANUAL
# - name: "MEDIUM | SV-252144 | MongoDB must associate organization-defined types of security labels having organization-defined security label values with information in storage and transmission."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252144

##### same ansible as 252149
- name: "MEDIUM | SV-252145 | MongoDB must enforce discretionary access control policies, as defined by the data owner, over defined subjects and objects."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.authorization
      value: enabled      
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252145

##### ENTERPRISE, Added a PII tag, this only needs to be run if there will be PII in the db
# - name: "MEDIUM | SV-252147 | MongoDB must implement cryptographic mechanisms to prevent unauthorized modification of organization-defined information at rest (to include, at a minimum, PII and classified information) on organization-defined information system components."
#   yedit:
#     src: "{{ mongod_config_path }}"
#     edits:
#     - key: security.enableEncryption
#       value: true
#     - key: kmip.serverName
#       value: "{{ KMIP_server_host_name }}"
#     - key: kmip.port
#       value: "{{ KMIP_server_port }}"
#     - key: kimp.ServerCAFile
#       value: "{{ KMIP_server_ca_file }}"
#     - key: kmip.clientCertificationFile
#       value: "{{ KMIP_client_certificate_file }}"
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252147
#     - enterprise
#     - pii

- name: "MEDIUM | SV-252148 | MongoDB must limit the total number of concurrent connections to the database."
  yedit:
    src: "{{ mongod_config_path }}"
    key: net.maxIncomingConnections
    value: "{{ max_incoming_connections }}"
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252148

##### MANUAL
# - name: "MEDIUM | SV-252151 | MongoDB must limit privileges to change software modules, to include stored procedures, functions and triggers, and links to software external to MongoDB."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252151

##### MANUAL
# - name: "MEDIUM | SV-252153 | Database software, including DBMS configuration files, must be stored in dedicated directories, or DASD pools, separate from the host OS and other applications."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252153

##### MANUAL ANSIBLE
# - name: "MEDIUM | SV-252154 | Database objects (including but not limited to tables, indexes, storage, stored procedures, functions, triggers, links to software external to MongoDB, etc.) must be owned by database/DBMS principals authorized for ownership."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252154

# - name: "MEDIUM | SV-252155 | The role(s)/group(s) used to modify database structure (including but not necessarily limited to tables, indexes, storage, etc.) and logic modules (stored procedures, functions, triggers, links to software external to MongoDB, etc.) must be restricted to authorized users."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252155

- name: "MEDIUM | SV-252156 | Unused database components that are integrated in MongoDB and cannot be uninstalled must be disabled."
  yedit:
    src: "{{ mongod_config_path }}"
    key: net.http
    state: absent
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252156

##### IS THIS ALSO NOT 252149 and 252145 BUT WITH A MANUAL CHECK???
# - name: "MEDIUM | SV-252157 | MongoDB must uniquely identify and authenticate organizational users (or processes acting on behalf of organizational users)."
#   yedit:
#       src: "{{ mongod_config_path }}"
#       key: security.authorization
#       value: enabled
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252157

##### manual??? this one is manual is postgres, but its also less specific 
# - name: "MEDIUM | SV-252161 | MongoDB must map the PKI-authenticated identity to an associated user account."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252161

##### in postgres the wording is the same but it seems like they check super users, but i dont think this one is checking for that? https://github.com/mitre/crunchy-data-postgresql-stig-baseline/blob/ca4a37b5179926d0e2b076d48125524b0faa0c3a/controls/V-233524.rb#L8
# - name: "MEDIUM | SV-252163 | MongoDB must uniquely identify and authenticate non-organizational users (or processes acting on behalf of non-organizational users)."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252163

##### NEEDS SOME FILE I DONT HAVE
# - name: "MEDIUM | SV-252164 | MongoDB must maintain the authenticity of communications sessions by guarding against man-in-the-middle attacks that guess at Session ID values."
#   yedit:
#     src: "{{ mongod_config_path }}"
#     key: net.tls.mode
#     value: requireTLS
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252164

##### MANUAL
# - name: "MEDIUM | SV-252166 | Database contents must be protected from unauthorized and unintended information transfer by enforcement of a data-transfer policy."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252166

- name: "MEDIUM | SV-252167 | MongoDB must check the validity of all data inputs except those specifically identified by the organization."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.javascriptEnabled
      value: false
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252167

- name: "MEDIUM | SV-252168 | MongoDB must provide non-privileged users with error messages that provide information necessary for corrective actions without revealing information that could be exploited by adversaries."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.redactClientLogData
      value: true
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252168

- name: "MEDIUM | SV-252169 | MongoDB must reveal detailed error messages only to the ISSO, ISSM, SA, and DBA."
  yedit:
      src: "{{ mongod_config_path }}"
      key: security.redactClientLogData
      value: true
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252169


##### MANUAL
# - name: "MEDIUM | SV-252170 | MongoDB must automatically terminate a user session after organization-defined conditions or trigger events requiring session disconnect."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252170

- name: "MEDIUM | SV-252171 | MongoDB must utilize centralized management of the content captured in audit records generated by all components of MongoDB."
  yedit:
    src: "{{ mongod_config_path }}"
    edits:
    - key: auditLog.destination
      value: file
    - key: auditLog.format
      value: BSON
    - key: auditLog.path
      value: "{{ mongo_audit_file_path }}"
    - key: auditLog.filter
      value: "'{ atype: { $in: [ \"createCollection\", \"dropCollection\" ] } }'"
  when: audit_log_destination == "file"
  ignore_errors: true
  tags:
    - cat2
    - medium
    - SV-252171
    - enterprise

##### MANUAL
# - name: "MEDIUM | SV-252172 | MongoDB must allocate audit record storage capacity in accordance with site audit record storage requirements."
#   yedit:
#     src: "{{ mongod_config_path }}"
#     key: auditLog.destination
#     value: "{{ audit_log_destination}}"
#   when: audit_log_destination == "syslog"
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252172
#     - enterprise

##### MANUAL
# - name: "MEDIUM | SV-252173 | MongoDB must provide a warning to appropriate support staff when allocated audit record storage volume reaches 75 percent of maximum audit record storage capacity."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252173
#     - enterprise

# - name: "MEDIUM | SV-252174 | MongoDB must prohibit user installation of logic modules (stored procedures, functions, triggers, views, etc.) without explicit privileged status."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252174

##### MANUAL 
# - name: "MEDIUM | SV-252175 | MongoDB must enforce access restrictions associated with changes to the configuration of MongoDB or database(s)."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252175

# - name: "MEDIUM | SV-252176 | MongoDB must require users to reauthenticate when organization-defined circumstances or situations require reauthentication."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252176

##### MANUAL
# - name: "MEDIUM | SV-252177 | MongoDB must prohibit the use of cached authenticators after an organization-defined time period."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252177

# - name: "MEDIUM | SV-252178 | MongoDB must only accept end entity certificates issued by DoD PKI or DoD-approved PKI Certification Authorities (CAs) for the establishment of all encrypted sessions."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252178

# - name: "MEDIUM | SV-252179 | MongoDB must maintain the confidentiality and integrity of information during preparation for transmission."
#   yedit:
#     src: "{{ mongod_config_path }}"
#     edits:
#     - key: net.tls.mode
#       value: requireTLS
#     - key: net.tls.certificateKeyFile
#       value: "{{ certificate_key_file_dest }}"
#     - key: net.tls.CAFile
#       value: "{{ ca_file_dest }}"
#     - key: net.tls.allowInvalidCertificates
#       value: false
#     - key: net.tls.allowConnectionsWithoutCertificates
#       value: false
#     - key: net.tls.FIPSMode
#       value: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252179

# - name: "MEDIUM | SV-252180 | MongoDB must maintain the confidentiality and integrity of information during reception."
  # yedit:
  #   src: "{{ mongod_config_path }}"
  #   edits:
  #   - key: net.tls.mode
  #     value: requireTLS
  #   - key: net.tls.certificateKeyFile
  #     value: "{{ certificate_key_file_dest }}"
  #   - key: net.tls.CAFile
  #     value: "{{ ca_file_dest }}"
  #   - key: net.tls.allowInvalidCertificates
  #     value: false
  #   - key: net.tls.allowConnectionsWithoutCertificates
  #     value: false
  #   - key: net.tls.FIPSMode
  #     value: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252180
#     - enterprise

##### MANUAL
# - name: "MEDIUM | SV-252181 | When invalid inputs are received, MongoDB must behave in a predictable and documented manner that reflects organizational and system objectives."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252181

# - name: "MEDIUM | SV-252182 | When updates are applied to MongoDB software, any software components that have been replaced or made unnecessary must be removed."
#   command: true
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252182

##### MANUAL
# - name: "MEDIUM | SV-252183 | Security-relevant software updates to MongoDB must be installed within the time period directed by an authoritative source (e.g., IAVM, CTOs, DTMs, and STIGs)."
#   command: true  
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252183

##### MANUAL
# - name: "MEDIUM | SV-252185 | MongoDB must be configured in accordance with the security configuration settings based on DoD security configuration and implementation guidance, including STIGs, NSA configuration guides, CTOs, DTMs, and IAVMs."
#   command: true 
#   ignore_errors: true
#   tags:
#     - cat2
#     - medium
#     - SV-252185

- name: Print the contents of mongod.conf
  command: cat "{{ mongod_config_path }}"
  register: mongod_conf_content

- name: Display contents of mongod.conf
  debug:
    msg: "{{ mongod_conf_content.stdout }}"
