---
# tasks file for mongo-stig
- name: Include CAT I
  ansible.builtin.import_tasks: cat1.yml
  when: mongostig_cat1
  tags:
      - CAT1
      - high

# - name: Include CAT II
#   ansible.builtin.import_tasks: cat2.yml
#   when: mongostig_cat2
#   tags:
#       - CAT2
#       - medium

# - name: Include CAT III
#   ansible.builtin.import_tasks: cat3.yml
#   when: mongostig_cat3
#   tags:
#       - CAT3
#       - low