---
- name: Mongo.conf Prep
  ansible.builtin.import_tasks: prep.yml
  when: prep_conf
  tags:
    - prep

- name: Enable FIPS Mode
  ansible.builtin.import_tasks: fips.yml
  when: fips_mode
  tags:
    - fips
    - enterprise

- name: Include CAT I
  ansible.builtin.import_tasks: cat1.yml
  when: mongostig_cat1
  tags:
    - CAT1
    - high

- name: Include CAT II
  ansible.builtin.import_tasks: cat2.yml
  when: mongostig_cat2
  tags:
    - CAT2
    - medium