on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_job:
    name: Harden ubi8 Container
    runs-on: ubuntu-latest
    env:
      foo: bar
    steps:
      - name: add dependencies
        run: |
          sudo apt-get update
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
          brew install docker
          brew install packer
          brew install ansible
          brew install mitre/saf/saf-cli
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - name: Clone repository in
        run: |
          git clone https://github.com/mitre/ubi8-hardening-demo.git
          pwd
          ls
      - name: run packer
        run: |
          packer init ubi8-hardening.pkr.hcl
          packer build .  
        working-directory: ~/ubi8-hardening-demo/
